"""
NLP Report Generation module.
Generates free-text radiology-style reports from prediction results using
template-based generation or LLM integration (OpenAI / local models).
"""

import os
import json
from datetime import datetime
from typing import Dict, Optional


# ====================== TEMPLATE-BASED REPORTS ======================

RADIOLOGY_TEMPLATE = """
CHEST X-RAY ANALYSIS REPORT
============================
Date: {date}
Report ID: {report_id}

CLINICAL INFORMATION:
  Examination: PA Chest Radiograph
  AI-Assisted Analysis

FINDINGS:
{findings}

IMPRESSION:
{impression}

SEVERITY ASSESSMENT:
  Classification: {severity}
  Confidence Level: {confidence:.1%}
  Affected Area: {affected_area:.1f}%

RECOMMENDATIONS:
{recommendations}

AI-GENERATED UNCERTAINTY ANALYSIS:
  Model Confidence: {confidence:.1%}
  {uncertainty_note}

DISCLAIMER:
  This report was generated by an AI-assisted pneumonia detection system.
  It is intended for screening purposes only and should NOT replace
  professional radiological interpretation. All findings should be
  reviewed and confirmed by a qualified radiologist or physician.

Report generated by: AI Pneumonia Detection System v2.0
"""

PATIENT_FRIENDLY_TEMPLATE = """
YOUR CHEST X-RAY RESULTS
=========================
Date: {date}

WHAT WE FOUND:
{patient_findings}

WHAT THIS MEANS:
{patient_explanation}

WHAT YOU SHOULD DO:
{patient_actions}

IMPORTANT:
  This is an AI screening tool. Please discuss these results with your
  doctor who can provide a thorough evaluation and proper diagnosis.
"""


def generate_findings_text(prediction: int, severity: str,
                           confidence: float, affected_area: float) -> str:
    """Generate radiology-style findings text."""
    if prediction == 0 or severity == 'Normal':
        return (
            "  The lung fields appear clear bilaterally. No focal consolidation,\n"
            "  pleural effusion, or pneumothorax is identified. The cardiac\n"
            "  silhouette and mediastinal contours are within normal limits.\n"
            "  No acute cardiopulmonary abnormality is detected."
        )
    
    severity_descriptions = {
        'Mild': (
            f"  There are subtle areas of increased opacity noted, predominantly\n"
            f"  in the lower lung zones, suggesting early pneumonic infiltration.\n"
            f"  Approximately {affected_area:.0f}% of the visualized lung parenchyma\n"
            f"  shows abnormal signal. No significant pleural effusion.\n"
            f"  The cardiac silhouette appears normal in size."
        ),
        'Moderate': (
            f"  There are patchy areas of consolidation identified in the lung fields,\n"
            f"  consistent with moderate pneumonia. Approximately {affected_area:.0f}%\n"
            f"  of the lung parenchyma demonstrates abnormal opacification.\n"
            f"  Air bronchograms may be present. Mild-to-moderate involvement\n"
            f"  of both lung bases is noted. Small pleural effusion cannot be excluded."
        ),
        'Severe': (
            f"  Diffuse bilateral pulmonary infiltrates are identified with extensive\n"
            f"  areas of consolidation involving approximately {affected_area:.0f}% of\n"
            f"  the visualized lung parenchyma. Dense consolidation is noted\n"
            f"  in multiple lobes with air bronchograms. Associated pleural\n"
            f"  effusion is likely. Findings are consistent with severe pneumonia.\n"
            f"  Consideration of ARDS should be made in the appropriate clinical context."
        ),
    }
    
    return severity_descriptions.get(severity, severity_descriptions['Moderate'])


def generate_impression_text(prediction: int, severity: str,
                             confidence: float) -> str:
    """Generate impression/conclusion text."""
    if prediction == 0 or severity == 'Normal':
        return "  No acute cardiopulmonary disease. Lungs are clear."
    
    impressions = {
        'Mild': f"  Findings suggestive of mild pneumonia. Clinical correlation recommended.",
        'Moderate': (
            f"  Findings consistent with moderate pneumonia. "
            f"Recommend clinical correlation,\n"
            f"  lab work (CBC, CRP), and consideration of antibiotic therapy."
        ),
        'Severe': (
            f"  Findings consistent with severe pneumonia with extensive bilateral\n"
            f"  involvement. URGENT clinical attention required. Consider ICU admission,\n"
            f"  broad-spectrum antibiotics, and supplemental oxygen."
        ),
    }
    
    return impressions.get(severity, impressions['Moderate'])


def generate_template_report(prediction: int, severity: str,
                             confidence: float, affected_area: float,
                             recommendations: Dict = None,
                             uncertainty_info: Dict = None,
                             report_format: str = 'radiology') -> str:
    """
    Generate a report using templates.
    
    Args:
        prediction: 0=Normal, 1=Pneumonia
        severity: Severity level
        confidence: Model confidence
        affected_area: Affected area percentage
        recommendations: Recommendation dict
        uncertainty_info: Uncertainty metrics dict
        report_format: 'radiology', 'patient_friendly', or 'both'
    
    Returns:
        Formatted report string
    """
    date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_id = f"RPT-{datetime.now().strftime('%Y%m%d%H%M%S')}"
    
    findings = generate_findings_text(prediction, severity, confidence, affected_area)
    impression = generate_impression_text(prediction, severity, confidence)
    
    # Format recommendations
    rec_text = ""
    if recommendations:
        for i, rec in enumerate(recommendations.get('recommendations', []), 1):
            rec_text += f"  {i}. {rec}\n"
    else:
        rec_text = "  Consult with treating physician for individualized recommendations."
    
    # Uncertainty note
    uncertainty_note = ""
    if uncertainty_info:
        is_uncertain = uncertainty_info.get('is_uncertain', False)
        if is_uncertain:
            uncertainty_note = (
                "⚠️ NOTE: The model shows elevated uncertainty for this case.\n"
                "  The prediction may be less reliable. Additional clinical review\n"
                "  is strongly recommended."
            )
        else:
            uncertainty_note = "Model confidence is within acceptable range."
    else:
        uncertainty_note = "Uncertainty quantification not performed."
    
    if report_format in ('radiology', 'both'):
        radiology_report = RADIOLOGY_TEMPLATE.format(
            date=date, report_id=report_id,
            findings=findings, impression=impression,
            severity=severity, confidence=confidence,
            affected_area=affected_area,
            recommendations=rec_text,
            uncertainty_note=uncertainty_note
        )
    
    if report_format in ('patient_friendly', 'both'):
        # Simplify for patients
        if prediction == 0 or severity == 'Normal':
            patient_findings = "Your chest X-ray looks normal. No signs of pneumonia were found."
            patient_explanation = "This is good news! Your lungs appear healthy based on this screening."
        else:
            patient_findings = f"The AI screening found signs that may indicate {severity.lower()} pneumonia."
            patient_explanation = (
                f"About {affected_area:.0f}% of your lung area shows some changes. "
                f"The AI system is {confidence:.0%} confident in this finding."
            )
        
        patient_actions = ""
        if recommendations:
            for i, rec in enumerate(recommendations.get('recommendations', [])[:5], 1):
                patient_actions += f"  {i}. {rec}\n"
        
        patient_report = PATIENT_FRIENDLY_TEMPLATE.format(
            date=date,
            patient_findings=patient_findings,
            patient_explanation=patient_explanation,
            patient_actions=patient_actions
        )
    
    if report_format == 'both':
        return radiology_report + "\n\n" + "=" * 50 + "\n\n" + patient_report
    elif report_format == 'patient_friendly':
        return patient_report
    else:
        return radiology_report


# ====================== LLM-BASED REPORTS ======================

def generate_llm_report(prediction: int, severity: str,
                        confidence: float, affected_area: float,
                        uncertainty_info: Dict = None,
                        backend: str = 'openai',
                        model_name: str = 'gpt-4',
                        api_key: str = None) -> str:
    """
    Generate a report using an LLM (OpenAI or local).
    
    Falls back to template-based generation if the LLM is unavailable.
    """
    prompt = _build_llm_prompt(prediction, severity, confidence,
                               affected_area, uncertainty_info)
    
    if backend == 'openai':
        return _call_openai(prompt, model_name, api_key)
    elif backend == 'local_llm':
        return _call_local_llm(prompt)
    else:
        # Fallback to template
        return generate_template_report(
            prediction, severity, confidence, affected_area,
            uncertainty_info=uncertainty_info
        )


def _build_llm_prompt(prediction, severity, confidence, affected_area,
                      uncertainty_info=None) -> str:
    """Build the prompt for LLM report generation."""
    return f"""You are an expert radiologist AI assistant. Generate a professional 
radiology report for a chest X-ray analysis with the following findings:

- Prediction: {'Pneumonia detected' if prediction == 1 else 'Normal (no pneumonia)'}
- Severity: {severity}
- AI Confidence: {confidence:.1%}
- Affected Lung Area: {affected_area:.1f}%
- Uncertainty: {'High - recommend additional review' if uncertainty_info and uncertainty_info.get('is_uncertain') else 'Within normal range'}

Generate a structured report with:
1. FINDINGS section (clinical descriptions)
2. IMPRESSION section (summary)  
3. RECOMMENDATIONS section
4. Include appropriate medical terminology
5. End with a disclaimer that this is AI-generated

Keep the report professional, concise, and clinically relevant."""


def _call_openai(prompt: str, model: str = 'gpt-4', api_key: str = None) -> str:
    """Call OpenAI API for report generation."""
    api_key = api_key or os.environ.get('OPENAI_API_KEY')
    
    if not api_key:
        return "[OpenAI API key not configured. Using template-based report.]"
    
    try:
        import openai
        client = openai.OpenAI(api_key=api_key)
        
        response = client.chat.completions.create(
            model=model,
            messages=[
                {"role": "system", "content": "You are an expert radiologist."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=500,
            temperature=0.3,
        )
        return response.choices[0].message.content
    
    except ImportError:
        return "[OpenAI package not installed. Run: pip install openai]"
    except Exception as e:
        return f"[LLM report generation failed: {e}]"


def _call_local_llm(prompt: str) -> str:
    """Placeholder for local LLM integration (e.g., llama.cpp, ONNX Runtime)."""
    return "[Local LLM not configured. Using template-based report.]"


# ====================== UNIFIED INTERFACE ======================

def generate_report(prediction: int, severity: str,
                    confidence: float, affected_area: float,
                    recommendations: Dict = None,
                    uncertainty_info: Dict = None,
                    backend: str = 'template',
                    report_format: str = 'radiology',
                    **kwargs) -> str:
    """
    Unified report generation interface.
    
    Args:
        prediction: 0=Normal, 1=Pneumonia
        severity: Severity level
        confidence: Model confidence
        affected_area: Affected area percentage
        recommendations: Recommendation dict
        uncertainty_info: Uncertainty metrics
        backend: 'template', 'openai', 'local_llm'
        report_format: 'radiology', 'patient_friendly', 'both'
    
    Returns:
        Generated report text
    """
    if backend == 'template':
        return generate_template_report(
            prediction, severity, confidence, affected_area,
            recommendations, uncertainty_info, report_format
        )
    else:
        llm_report = generate_llm_report(
            prediction, severity, confidence, affected_area,
            uncertainty_info, backend,
            model_name=kwargs.get('model_name', 'gpt-4'),
            api_key=kwargs.get('api_key')
        )
        # If LLM failed, fallback to template
        if llm_report.startswith('['):
            fallback = generate_template_report(
                prediction, severity, confidence, affected_area,
                recommendations, uncertainty_info, report_format
            )
            return llm_report + "\n\n--- TEMPLATE FALLBACK ---\n" + fallback
        return llm_report


if __name__ == "__main__":
    # Test report generation
    report = generate_report(
        prediction=1, severity='Moderate',
        confidence=0.85, affected_area=32.5,
        report_format='both'
    )
    print(report)
